services:
  zebra-print:
    build: 
      context: .
      dockerfile: Dockerfile.smart
    container_name: zebra-print-control
    restart: unless-stopped
    
    # USB printer access
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    
    # Dynamic port mapping (script will handle conflicts)
    ports:
      - "${ZEBRA_API_PORT:-5000}:${ZEBRA_CONTAINER_API_PORT:-5000}"
      - "${ZEBRA_CUPS_PORT:-8631}:631"
    
    # Volumes for persistence
    volumes:
      - zebra_data:/app/data
      - zebra_logs:/var/log/zebra-print
      - /dev:/dev:ro  # Device access
    
    # Environment variables (with smart defaults)
    environment:
      - ZEBRA_API_HOST=0.0.0.0
      - ZEBRA_API_PORT=${ZEBRA_API_PORT:-5000}
      - ZEBRA_CONTAINER_API_PORT=${ZEBRA_CONTAINER_API_PORT:-5000}
      - ZEBRA_PRINTER_NAME=ZTC-ZD230-203dpi-ZPL
      - ZEBRA_DB_PATH=/app/data/zebra_print.db
      - TZ=UTC
    
    # Health check with dynamic port
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:$${ZEBRA_CONTAINER_API_PORT:-5000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  zebra_data:
    driver: local
  zebra_logs:
    driver: local

# For easier management
networks:
  default:
    name: zebra-print-network