version: '3.8'

services:
  zebra-print:
    build: 
      context: .
      dockerfile: Dockerfile.alpine
    container_name: zebra-print-control-alpine
    restart: unless-stopped
    
    # USB printer access
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    
    # Network ports
    ports:
      - "5000:5000"  # API server
      - "631:631"    # CUPS web interface
    
    # Volumes for persistence (much smaller footprint)
    volumes:
      - zebra_data_alpine:/app/data
      - zebra_logs_alpine:/var/log/zebra-print
      - /dev:/dev:ro
    
    # Environment variables
    environment:
      - ZEBRA_API_HOST=0.0.0.0
      - ZEBRA_API_PORT=5000
      - ZEBRA_PRINTER_NAME=ZTC-ZD230-203dpi-ZPL
      - ZEBRA_DB_PATH=/app/data/zebra_print.db
      - TZ=UTC
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  zebra_data_alpine:
    driver: local
  zebra_logs_alpine:
    driver: local

networks:
  default:
    name: zebra-print-network-alpine