version: '3.8'

services:
  zebra-print:
    image: kodemeio/zebra-pdf:latest
    container_name: zebra-print-control
    restart: unless-stopped
    
    # USB printer access - full device access
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    
    # Port mapping for production
    ports:
      - "5000:5000"
      - "631:631"
    
    # Volumes for persistence and device access
    volumes:
      - zebra_data:/app/data
      - zebra_logs:/var/log/zebra-print
      - /dev:/dev  # Full device access (not read-only)
      - /run/udev:/run/udev:ro  # udev access for device detection
    
    # Environment variables - loaded from .env file
    env_file: .env
    environment:
      - ZEBRA_API_HOST=${ZEBRA_API_HOST:-0.0.0.0}
      - ZEBRA_API_PORT=${ZEBRA_API_PORT:-5000}
      - ZEBRA_PRINTER_NAME=${ZEBRA_PRINTER_NAME:-ZTC-ZD230-203dpi-ZPL}
      - ZEBRA_DB_PATH=/app/data/zebra_print.db
      - ZEBRA_API_TOKEN=${ZEBRA_API_TOKEN}
      - ZEBRA_DOMAIN=${ZEBRA_DOMAIN}
      - ZEBRA_TUNNEL_TYPE=${ZEBRA_TUNNEL_TYPE}
      - TZ=${TZ:-UTC}
      - PYTHONPATH=/app
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Host access for better hardware integration
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    # Networks
    networks:
      - public
    
    # Labels for easier management
    labels:
      - "project=zebra-print"
      - "service=api"
      - "environment=production"

volumes:
  zebra_data:
    driver: local
  zebra_logs:
    driver: local

networks:
  public:
  dokploy-network:
    external: true